---
# SPDX-FileCopyrightText: (c) 2021 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileType: SOURCE
name: "REUSE Compliance Check"
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  reuse:
    name: "REUSE Compliance Check"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "REUSE Compliance Check"
        uses: fsfe/reuse-action@v1
